### ISSUE TITLE
Can't figure out how to proceed in the installation 

### ISSUE THREAD

**Issue by AmihaiN** [IHTSDO/snow-owl#33]
I was following the installation guide (https://github.com/IHTSDO/snow-owl/blob/master/documentation/src/main/asciidoc/installation_guide.adoc) but got stuck on the last part where it asks me to unzip the snowowl-community zip (unzip snowowl-community-{version}-mysql.zip -d /opt).

I'm not sure where to get this zip file and how to proceed from here with the installation. the guide is pretty confusing :(

**Comment by kaicode** [comment]
Hi Amihai,
The zip file mentioned in the guide is the distribution of the Snow Owl application.
After running the maven build the zip file will be available in the releng/distribution/target/ directory.
Maven build instructions are here - https://github.com/IHTSDO/snow-owl/#build
I hope this helps.
Kai
