### ISSUE TITLE
Not able to locate LDAP packages provided by B2i

### ISSUE THREAD

**Issue by dhirendras** [IHTSDO/snow-owl#52]
I was following the Installation guide given in https://github.com/b2ihealthcare/snow-owl/blob/6.x/documentation/src/main/asciidoc/ for setup of snow-owl terminology server, while Configuring LDAP i was not able to locate LDAP package and LDIF dumps.
Kindly help me in locating the files.

**Comment by kaicode** [comment]
Hi @dhirendras. Snomed International does not use LDAP so we don't have any experience with this. Please contact B2i directly for help with this. Raising an issue in the upstream repository seems appropriate. Thank you.
