### ISSUE TITLE
Can't figure out Proper Creation of New Concept and related mrcm rules for validation

### ISSUE THREAD

**Issue by dhirendraps** [IHTSDO/snow-owl#69]
We are setting up the Authoring-Platform and completed the integration of authroing-service, termserver and all other supporting services. After doing international import on the main branch of termserver. While creating new concepts on the sub-branch and adding "is a(attribute)" to the concept, it will check the mrcm rules but unable to find it.
We have already added the path of mrcm rules directory before starting the termserver.
I am attaching the screenshot of my browser which will clear the test case i am trying. 
Please guide in understanding the flow of concept creation and the how to properly apply mrcm rules.

![screenshot 50 _li](https://user-images.githubusercontent.com/43638925/50688316-f4ab4480-104a-11e9-82bc-03440a767f04.jpg)

**Comment by kaicode** [comment]
Hi @dhirendraps, the MRCM XML file must be imported into Snow Owl before the MRCM API endpoints will work. Please see the documentation for that [here](https://github.com/IHTSDO/snow-owl/blob/master/documentation/src/main/asciidoc/administrative_console_reference.adoc#import-mrcm-rules-from-xmi-file). The XML file is available [here](https://github.com/IHTSDO/termserver-mrcm-xml/blob/master/international/mrcm.xmi).

To connect to the Snow Owl OSGi command line go onto the command line of the machine running Snow Owl and then use telnet to connect. With the default configuration this will work: `telnet -l admin localhost 2501`

**Comment by dhirendraps** [comment]
Hi @kaicode, thank you for your reply. We have already imported the MRCM XML file in Snow Owl through Snow Owl OSGI. But when I am trying to hit "GET /mrcm/{path}/attribute-values/{attributeId}" endpoint of MRCM API and passing value to the {path} other than MAIN branch then it is not able to find the resource.

eg. 
"https://snomed-authoring.mig.in/snowowl/snomed-ct/v2/mrcm/MAIN/NTP/NTP-2/attribute-values/116680003?termPrefix=foot*&expand=fsn()&offset=0&limit=50" 
For the given API endpoint, I am getting 
{ developerMessage: "The requested instance resource (id = '116680003', type = 'MRCM predicate for attribute') does not exist and/or not yet created."
message: "MRCM predicate for attribute with identifier '116680003' could not be found."
status: 404 }

"https://snomed-authoring.mig.in/snowowl/snomed-ct/v2/mrcm/MAIN/attribute-values/116680003?termPrefix=foot*&expand=fsn()&offset=0&limit=50"
For the Same API endpint with {path} as MAIN i am getting proper repsonse.

As we have imported our International RF2 file on MAIN, do we need to import those files on the sub-branches also??

**Comment by kaicode** [comment]
Hi @dhirendraps, the MRCM content is like content on a branch. After the MRCM content is imported onto the MAIN branch you can merge it to child branches to make it visible. In your example if you merge `MAIN` to `MAIN/NTP` and then merge `MAIN/NTP` to `MAIN/NTP/NTP-2` then the MRCM content will be available on the NTP-2 branch.

**Comment by dhirendraps** [comment]
Thank you @kaicode, it is very helpful and solved my issue.

**Comment by kaicode** [comment]
I'm glad your implementation started working 😄

**Comment by dhirendraps** [comment]
Hi @kaicode , When i am trying to save the newly created concept. It is giving 
"Fatal error: Could not validate concept" and 
Response as : {"status":400,"code":0,"message":"No assertion groups configured for this branch.","developerMessage":"Input representation syntax or validation errors. Check input values."}

I have already integrated the RVF API through Orchestration service. How can i configure Assertion groups for a particular branch?

**Comment by kaicode** [comment]
Hi @dhirendraps, this error is related to the integration of the [SNOMED Drools validation engine](https://github.com/IHTSDO/snomed-drools).

One or more assertion groups must be configured in the branch metadata so the Drools validation engine knows which rule sets to use for validation during save.

The [SNOMED Drools Rules](https://github.com/IHTSDO/snomed-drools-rules) should be checked out into the Snow Owl installation directory, for example `/opt/termserver/snomed-drools-rules`. This location is configurable in `snowowl_config.yml` using snomed > drools > rulesDirectory. The rules are read into Snow OWL during startup.

A key/value pair needs to be set in the metadata of the MAIN branch to configure which rule assertion groups to run. Here is example branch metadata:
```
"metadata": {
    "assertionGroupNames": "common-authoring",
    "previousRelease": "20190131",
    "defaultReasonerNamespace": "",
    "classification.previousPackage": "prod_main_20190131_20181109133000.zip"
}
```

**Comment by dhirendraps** [comment]
Hi @kaicode, 

Please let me know what current version of the components worked for Snomed International in production and also  tell me about current version of Ansible.

And while running the termserver it not able to retrieve "cs_words.txt, gbTerms.txt and usTerms.txt" files from the location "/opt/termserver/resources/test-resources/". I have checked for the files they are not present at given location. I trying searching these files but not able to get them please provide these files.

When we start authoring platform it check's validation status for all the branches and sub-branches and it is not getting status.json at the given bucket. As i am using Offline S3ClientImpl and it not creating the status.json file. So my question for this is do we need to put status.json files manually for every branch. Please help me at this.

**Comment by kaicode** [comment]
Hi @dhirendraps,

The latest versions of components are listed on the [Authoring Platform 3.3.0 release notes](https://confluence.ihtsdotools.org/display/AUTHS/Authoring+Platform+Version+3.3.0+-+12+December+2018+-+Release+Notes).

We store the test resource files in S3. I've created a copy in git gist, please take a copy of these files for your own deployment. The files required for the current production deployment are [cs_words.txt](https://gist.githubusercontent.com/kaicode/eff28e7273548eec474ef980961dd65b/raw/f09d4501ad72c86958651e0001fbb61d2da9ea98/cs_words.txt), [gbTerms.txt](https://gist.githubusercontent.com/kaicode/a57558ec0bf21b57f16f2584f2fb7540/raw/0ffd69ba574acec1788efc12bd3275068f2cf1c1/gbTerms.txt), [usTerms.txt](https://gist.githubusercontent.com/kaicode/4c61500485353893c95d1ff533746ab7/raw/5b2691400c592d0129f14772404ab704dbeb869f/usTerms.txt).

The Orchestration Service checks the branch status. If validation has never been run it may log a message but we currently ignore this. The authoring UI should show no validation icon against tasks which have never been validated.

I hope that helps.

**Comment by dhirendraps** [comment]
Hi @kaicode, while creating a concept if 
Use case:
FSN as preferred for us and gb
SYN as preferred for us and gb
SYN as acceptable for us and gb

then concept get saved without issue.
![screenshot 55](https://user-images.githubusercontent.com/43638925/51476757-7372e200-1dac-11e9-8983-d0d08d4fcc88.png)

Use case:
FSN as preferred for us and gb
SYN as acceptable for us and gb
SYN as preferred for us and gb
then concept through error
"[2019-01-21 18:44:37.094] ERROR http-bio-8080-exec-2         c.b.snowowl.snomed.api.rest.ControllerExceptionMapper             Exception during request processing com.b2international.snowowl.core.api.SnowowlRuntimeException: com.b2international.snowowl.core.api.SnowowlRuntimeException: com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key com.b2international.snowowl.datastore.server.internal.CDOTransactionContext@75c03dae."
![screenshot 54](https://user-images.githubusercontent.com/43638925/51476849-b8971400-1dac-11e9-845b-97f3f3c8b391.png)

**Comment by kaicode** [comment]
Hi @dhirendraps,
I'm sorry I do not recognise this issue. You could either take a look at the Snow Owl source code which is [available on github](https://github.com/IHTSDO/snow-owl) or get in touch with [B2i Healthcare](http://b2i.sg/contact/contact-us/) who are able to provide detailed support and debugging for this application.
